data_sources:
    - global_emissions
    - pib
    - population
    - renewable_energy

api_urls:
  - renewable_energy: 
      name: renewable_energy
      url: https://api.worldbank.org/v2/en/indicator/EG.ELC.RNEW.ZS?downloadformat=excel
      extension: xls
  - population:
      name: population
      url: https://www.kaggle.com/api/v1/datasets/download/iamsouravbanerjee/world-population-dataset
      extension: zip
  - global_emissions:
      name: global_emissions
      url: https://www.kaggle.com/api/v1/datasets/download/unitednations/international-greenhouse-gas-emissions
      extension: zip
  - pib:
      name: pib
      url: https://www.rug.nl/ggdc/historicaldevelopment/maddison/data/mpd2020.xlsx
      extension: xlsx

download:
    renewable_energy: 
        url: https://api.worldbank.org/v2/en/indicator/EG.ELC.RNEW.ZS?downloadformat=excel
        path: data/renewable_energy/renewable_energy.xls
    population:
        url: https://www.kaggle.com/api/v1/datasets/download/iamsouravbanerjee/world-population-dataset
        path: data/population/population.zip
    global_emissions:
        url: https://www.kaggle.com/api/v1/datasets/download/unitednations/international-greenhouse-gas-emissions
        path: data/global_emissions/global_emissions.zip
    pib:
      url: https://www.rug.nl/ggdc/historicaldevelopment/maddison/data/mpd2020.xlsx
      path: data/pib/pib.xlsx

data_dir:
    root_dir: data
    global_emissions: 
        folder: global_emissions
        file: global_emissions
        extension: csv
    pib: 
        folder: pib
        file: pib
        extension: xlsx
    population: 
        folder: population
        file: population
        extension: csv
    renewable_energy: 
        folder: renewable_energy
        file: renewable_energy
        extension: xls

    outputs:
        root: output
        database: etl_output.db
        csv: 
            countries: countries.csv
            continents: continents.csv